"""empty message

Revision ID: 3c3fd52953ce
Revises: e86fabe715a4
Create Date: 2024-10-17 19:09:11.414291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3fd52953ce'
down_revision = 'e86fabe715a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('arquivo_pdf', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_constraint('professor_matricula_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_professor_matricula'), ['matricula'], unique=True)

    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_limite_edicao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.drop_column('data_limite_edicao')

    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professor_matricula'))
        batch_op.create_unique_constraint('professor_matricula_key', ['matricula'])

    op.drop_table('edital')
    # ### end Alembic commands ###
