"""empty message

Revision ID: fb7d2f992dd0
Revises: 
Create Date: 2025-01-06 10:05:29.758680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7d2f992dd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('permissao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aluno',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('curso', sa.String(length=255), nullable=False),
    sa.Column('data_ingresso', sa.DateTime(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('permissao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('professor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('curso', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('permissao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professor_matricula'), ['matricula'], unique=False)

    op.create_table('edital',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('arquivo_pdf', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('projeto',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('professor_id', sa.String(length=36), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('titulacao', sa.String(length=255), nullable=False),
    sa.Column('curso', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('linhaDePesquisa', sa.String(length=255), nullable=False),
    sa.Column('situacao', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('palavrasChave', sa.String(length=255), nullable=False),
    sa.Column('localizacao', sa.String(length=255), nullable=False),
    sa.Column('populacao', sa.String(length=255), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('objetivoGeral', sa.Text(), nullable=False),
    sa.Column('objetivoEspecifico', sa.Text(), nullable=False),
    sa.Column('metodologia', sa.Text(), nullable=False),
    sa.Column('cronogramaDeAtividade', sa.Text(), nullable=False),
    sa.Column('referencias', sa.Text(), nullable=False),
    sa.Column('termos', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('data_limite_edicao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_projeto',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('projeto_id', sa.String(length=36), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno_projeto')
    op.drop_table('projeto')
    op.drop_table('edital')
    with op.batch_alter_table('professor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professor_matricula'))

    op.drop_table('professor')
    op.drop_table('aluno')
    op.drop_table('admin')
    # ### end Alembic commands ###
